[package]
name = "view"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos.workspace = true

[features]
default = ["ssr"]
ssr = ["leptos/ssr"]
hydrate = ["leptos/hydrate"]


